### ISSUE TITLE
Country code issue

### ISSUE THREAD

**Issue by HuseyinFiliz** [TrianguloY/OpenInWhatsapp_Translation#64]
The "country code" setting in the "behavior" section of the settings does not work properly.

After entering the country code in this field, it does not save.

![Screenshot_20241009_143743_Click to chat](https://github.com/user-attachments/assets/6a45a1bb-be53-4703-9659-e8d9da0709e6)

**Comment by TrianguloY** [comment]
Uh? 
I swear I tested that...strange.
Thanks for the report! Hopefully should be easy to fix.

**Comment by HuseyinFiliz** [comment]
The new settings page, which is unrelated to the main topic, seems too complicated to me. I think it could have been divided into "Basic Settings" and "Advanced Settings." When the settings button is pressed from the main screen, only the basic settings would open, and there would be an "Advanced Settings" button below the basic settings. This way, it would provide a simpler experience for users who don't need to deal with the "behavior" section.

For such a simple application, I find the settings page too complex.

**Comment by TrianguloY** [comment]
It was already too complex, that's true. The current "grouping" was just a way to avoid having such a long list of options.
For a very simple application the amount of options is big...but I like to allow the user to configure things :)

The distinction into "basic" and "advanced" does actually makes a lot of sense, and I think I'll use that instead of the current "behavior" and "interface".

What settings so you thing should be in the "basic" section?

**Comment by HuseyinFiliz** [comment]
First of all, when the Basic, Advanced, and Addon sections are all expanded, the settings page becomes even longer because an additional heading is added for each section. Instead, you could consider organizing these headings into tabs and pinning them at the top. Since English isn't my native language, if my explanation isn't clear enough, I can draw a template to show you what I mean. But in summary, I suggest using a "topbar."

To address your issue, let's start with the Basic Settings:

Settings | **Basic** | Advanced | Addons

- Hide the help text...
- Restore prefix...
- Merge prefix...
- Remove leading zeros...
- Save recent numbers/messages...
- Use light theme...
- You can change the app language...

**Comment by HuseyinFiliz** [comment]
Hey there?

**Comment by TrianguloY** [comment]
I understand the tabs concept, I'll try to implement it for the next version if possible, as well as the distinction between basic/advanced.

But the distinction may not be as clear, I would have added the Remove leading zeros as advanced, and I'm not sure if Restore prefix is as basic either...
I'll think about that, in any case thanks for your opinion.

Btw, the fix for the restore prefix is in review now. If you get it and you can confirm it works, please close this task as completed (I'll close it myself in a few days otherwise)

**Comment by HuseyinFiliz** [comment]
![Screenshot_20241010_194105_Click to chat](https://github.com/user-attachments/assets/d88ab5f7-3704-4364-8623-9d1a56d52ff3)

I’ve applied the update, and I can confirm that the issue is now resolved. However, I noticed something interesting when using the app in Turkish: the country code field doesn’t have borders. When I considered taking a screenshot to explain this more easily in English, I saw that the borders for the country code field appear correctly when the app is in English.

It's an interesting situation, though it’s not critical for the usability of the app. I just wanted to share this observation with you, as it’s curious that the appearance differs between languages.

**Comment by TrianguloY** [comment]
I see, that could be due to the text length difference, which may hide part of the input. It may also happen with smaller screens.
Since it's not critical ink not going to upload another fix, but in any case I'll take a look to see if it can be fixed anyway.

Thanks for the confirmation!
